project:
  type: website
  output-dir: docs

  # This tells Quarto to ONLY render the dashboard and ignore the .py scripts
  render:
    - "*.qmd"
    - "!scripts/"

website:
  title: "FabCore Dashboard 2026"

# Global Engine: All files will use your portable venv kernel
jupyter: 
 kernelspec:
    name: "winpython3.12_fabcore"
    language: "python"
    display_name: "WPy3.12 for FabDash"

format:
  dashboard:
    orientation: columns
    theme: lux
    #logo: logo.png  # Optional: adds professional touch

# This is the "Magic" portable line
env:
  QUARTO_PYTHON: ".venv/Scripts/python.exe"

execute:
  enabled: true # On your local machine, you can set this to false to avoid double-runs. But for GitHub Actions, we will set it to true (see below)
  daemon: 0 # This keeps Quarto's temporary files INSIDE the repo folder. This fixes the C: drive permission issues for everyone!
  echo: false # to hide all of the executable source code used to produce dynamic outputs.
  # freeze: auto  # Only re-renders .qmd files if they have changed