project:
  type: website
  output-dir: docs

website:
  title: "FabCore Dashboard 2026"
#  to hide all of the executable source code used to produce dynamic outputs.
execute:
  echo: false

# Global Engine: All files will use your portable venv kernel
#jupyter: fabcore-dashboard2026

format:
  dashboard:
    orientation: columns
    theme: lux
    #logo: logo.png  # Optional: adds professional touch